---
- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- include: hostname.yml tags=hostname
  when : datacenter == 'Biznet'

- include: users.yml tags=useradd
- include: common_pkg.yml tags=commonpkg
- include: cron.yml tags=cron
- include: locale_tz.yml tags=locale
- include: security_update.yml tags=secupdate
- include: transparent-huge-page.yml tags=transparent-huge-page

- include: fixgcp.yml tags=fixgcp
  when : (datacenter == "GCP")
