---
#- name: Set resolve.conf in Aliyun
#  template: src=tail.j2 dest=/etc/resolvconf/resolv.conf.d/tail

- name: remove resolveconf file 
  file: path='/etc/dhcp/dhclient-enter-hooks.d/resolvconf' state=absent

- name: copy file script nodnsupdate
  template: src=nodnsupdate.j2 dest=/etc/dhcp/dhclient-enter-hooks.d/nodnsupdate mode=0774

- name: Update resolve.conf
  shell: resolvconf -u

