---
- name: disable transparent hugepage
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

- name: disable transparent hugepage
  shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable transparent hugepage on reboot
  lineinfile: dest=/etc/rc.local insertbefore="exit 0" line="{{ item }}"
  with_items:
     - echo never > /sys/kernel/mm/transparent_hugepage/enabled
     - echo never > /sys/kernel/mm/transparent_hugepage/defrag
  tags: OnBoot
